strictness: high
max-line-length: 120
autodetect: true

ignore-paths:
    - dengraph_examples
    - dengraph_unittests

pep8:
  disable:
    # first argument of a classmethod should be named 'cls'
    - N804
    # first argument of a method should be named 'self'
    - N805
